declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react'
  
  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: string | number
    color?: string
    strokeWidth?: string | number
  }

  export type Icon = ComponentType<IconProps>

  export const Lock: Icon
  export const Users: Icon
  export const TrendingUp: Icon
  export const Calendar: Icon
  export const AlertTriangle: Icon
  export const Briefcase: Icon
  export const FileText: Icon
  export const Eye: Icon
  export const BarChart3: Icon
  export const Shield: Icon
  export const Key: Icon
  export const DollarSign: Icon
  export const LineChart: Icon
  export const Wallet: Icon
  export const ArrowUpRight: Icon
  export const ArrowDownRight: Icon
  export const Percent: Icon
  export const Settings: Icon
  export const MessageSquare: Icon
  export const PieChart: Icon
  export const Target: Icon
  export const Zap: Icon
  export const Bell: Icon
  export const ChevronRight: Icon
  export const Brain: Icon
  export const Lightbulb: Icon
  export const Rocket: Icon
  export const Network: Icon
  export const Database: Icon
  export const Code: Icon
  export const TestTube: Icon
  export const Flask: Icon
  export const Microscope: Icon
  export const Search: Icon
  export const Layers: Icon
  export const GitBranch: Icon
  export const GitPullRequest: Icon
  export const GitCommit: Icon
  export const GitMerge: Icon
  export const Terminal: Icon
  export const Server: Icon
  export const Cloud: Icon
  export const Cpu: Icon
  export const Memory: Icon
  export const HardDrive: Icon
  export const Activity: Icon
  export const Pulse: Icon
  export const Heart: Icon
  export const ShieldCheck: Icon
  export const AlertCircle: Icon
  export const CheckCircle: Icon
  export const XCircle: Icon
  export const Clock: Icon
  export const Timer: Icon
  export const CalendarDays: Icon
  export const BarChart2: Icon
  export const LineChartIcon: Icon
  export const PieChartIcon: Icon
  export const ScatterChart: Icon
  export const AreaChart: Icon
  export const CandlestickChart: Icon
  export const TrendingDown: Icon
  export const TrendingUpIcon: Icon
  export const ArrowRight: Icon
  export const ArrowLeft: Icon
  export const ArrowUp: Icon
  export const ArrowDown: Icon
  export const Maximize: Icon
  export const Minimize: Icon
  export const ZoomIn: Icon
  export const ZoomOut: Icon
  export const RotateCcw: Icon
  export const RefreshCw: Icon
  export const Play: Icon
  export const Pause: Icon
  export const Stop: Icon
  export const SkipBack: Icon
  export const SkipForward: Icon
  export const FastForward: Icon
  export const Rewind: Icon
  export const Volume2: Icon
  export const VolumeX: Icon
  export const Volume1: Icon
  export const Mute: Icon
  export const Unmute: Icon
  export const Mic: Icon
  export const MicOff: Icon
  export const Video: Icon
  export const VideoOff: Icon
  export const Camera: Icon
  export const CameraOff: Icon
  export const Image: Icon
  export const ImageOff: Icon
  export const File: Icon
  export const FileTextIcon: Icon
  export const FilePlus: Icon
  export const FileMinus: Icon
  export const FileCheck: Icon
  export const FileX: Icon
  export const FileSearch: Icon
  export const FileCode: Icon
  export const FileJson: Icon
  export const FileType: Icon
  export const FileArchive: Icon
  export const FileAudio: Icon
  export const FileVideo: Icon
  export const FileImage: Icon
  export const FileSpreadsheet: Icon
  export const FileDatabase: Icon
  export const FilePdf: Icon
  export const FileWord: Icon
  export const FileExcel: Icon
  export const FilePowerpoint: Icon
  export const FileZip: Icon
  export const FileCog: Icon
  export const FileSettings: Icon
  export const FileQuestion: Icon
  export const FileWarning: Icon
  export const FileAlert: Icon
  export const FileInfo: Icon
  export const FileHelp: Icon
  export const FileHeart: Icon
  export const FileStar: Icon
  export const FileUp: Icon
  export const FileDown: Icon
  export const FileLeft: Icon
  export const FileRight: Icon
  export const FileInput: Icon
  export const FileOutput: Icon
  export const FileUpload: Icon
  export const FileDownload: Icon
  export const FileShare: Icon
  export const FileLock: Icon
  export const FileUnlock: Icon
  export const FileKey: Icon
  export const FileKeyhole: Icon
  export const FileCheckCircle: Icon
  export const FileXCircle: Icon
  export const FileAlertCircle: Icon
  export const FileInfoCircle: Icon
  export const FileHelpCircle: Icon
  export const FileHeartCircle: Icon
  export const FileStarCircle: Icon
  export const FileUpCircle: Icon
  export const FileDownCircle: Icon
  export const FileLeftCircle: Icon
  export const FileRightCircle: Icon
  export const FileInputCircle: Icon
  export const FileOutputCircle: Icon
  export const FileUploadCircle: Icon
  export const FileDownloadCircle: Icon
  export const FileShareCircle: Icon
  export const FileLockCircle: Icon
  export const FileUnlockCircle: Icon
  export const FileKeyCircle: Icon
  export const FileKeyholeCircle: Icon
  export const FileCheckSquare: Icon
  export const FileXSquare: Icon
  export const FileAlertSquare: Icon
  export const FileInfoSquare: Icon
  export const FileHelpSquare: Icon
  export const FileHeartSquare: Icon
  export const FileStarSquare: Icon
  export const FileUpSquare: Icon
  export const FileDownSquare: Icon
  export const FileLeftSquare: Icon
  export const FileRightSquare: Icon
  export const FileInputSquare: Icon
  export const FileOutputSquare: Icon
  export const FileUploadSquare: Icon
  export const FileDownloadSquare: Icon
  export const FileShareSquare: Icon
  export const FileLockSquare: Icon
  export const FileUnlockSquare: Icon
  export const FileKeySquare: Icon
  export const FileKeyholeSquare: Icon
} 